-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------

USE CATALOG `abccompany`;
USE SCHEMA `fixeddata`;

-- COMMAND ----------

SELECT COUNT(*) FROM abccompany.fixeddata.bs_product_master;

-- COMMAND ----------

DESCRIBE abccompany.fixeddata.bs_product_master;

-- COMMAND ----------

SELECT *
FROM abccompany.fixeddata.sl_geo_hierarchy
ORDER BY geo_level
LIMIT 10;

-- COMMAND ----------

SELECT *
FROM abccompany.fixeddata.sl_geo_hierarchy_resolved
ORDER BY territory_code
LIMIT 20;

-- COMMAND ----------

select * from abccompany.fixeddata.sl_market_definition;
